// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 03/12/2025, 10:37:17
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg4 from "./../../woonuxt_base/tailwind.config.ts";
const config = [
{"content":{"files":["C:/laragon/www/calzolaiomanu-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","./components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/plugins/**/*.{js,ts,mjs}","C:/laragon/www/calzolaiomanu-frontend/composables/**/*.{js,ts,mjs}","C:/laragon/www/calzolaiomanu-frontend/utils/**/*.{js,ts,mjs}","C:/laragon/www/calzolaiomanu-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/app.config.{js,ts,mjs}"]}},
{},
{"content":{"files":["C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/plugins/**/*.{js,ts,mjs}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/composables/**/*.{js,ts,mjs}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/utils/**/*.{js,ts,mjs}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/app.config.{js,ts,mjs}","C:/laragon/www/calzolaiomanu-frontend/woonuxt_base/app/spa-loading-template.html"]}},
cfg4
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;