
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AccountMyDetails': typeof import("../../woonuxt_base/app/components/AccountMyDetails.vue")['default']
  'CategoryCard': typeof import("../../woonuxt_base/app/components/CategoryCard.vue")['default']
  'DownloadList': typeof import("../../woonuxt_base/app/components/DownloadList.vue")['default']
  'DownloadableItems': typeof import("../../woonuxt_base/app/components/DownloadableItems.vue")['default']
  'LangSwitcher': typeof import("../../woonuxt_base/app/components/LangSwitcher.vue")['default']
  'OrderList': typeof import("../../woonuxt_base/app/components/OrderList.vue")['default']
  'SignInLink': typeof import("../../woonuxt_base/app/components/SignInLink.vue")['default']
  'WPAdminLink': typeof import("../../woonuxt_base/app/components/WPAdminLink.vue")['default']
  'WishListItem': typeof import("../../woonuxt_base/app/components/WishListItem.vue")['default']
  'CartCard': typeof import("../../woonuxt_base/app/components/cartElements/CartCard.vue")['default']
  'CartTrigger': typeof import("../../woonuxt_base/app/components/cartElements/CartTrigger.vue")['default']
  'CloseIcon': typeof import("../../woonuxt_base/app/components/cartElements/CloseIcon.vue")['default']
  'EmptyCart': typeof import("../../woonuxt_base/app/components/cartElements/EmptyCart.vue")['default']
  'QuantityInput': typeof import("../../woonuxt_base/app/components/cartElements/QuantityInput.vue")['default']
  'SwipeCard': typeof import("../../woonuxt_base/app/components/cartElements/SwipeCard.vue")['default']
  'TrashIcon': typeof import("../../woonuxt_base/app/components/cartElements/TrashIcon.vue")['default']
  'CategoryFilter': typeof import("../../woonuxt_base/app/components/filtering/CategoryFilter.vue")['default']
  'ColorFilter': typeof import("../../woonuxt_base/app/components/filtering/ColorFilter.vue")['default']
  'Filters': typeof import("../../woonuxt_base/app/components/filtering/Filters.vue")['default']
  'GlobalFilter': typeof import("../../woonuxt_base/app/components/filtering/GlobalFilter.vue")['default']
  'OnSaleFilter': typeof import("../../woonuxt_base/app/components/filtering/OnSaleFilter.vue")['default']
  'PriceFilter': typeof import("../../woonuxt_base/app/components/filtering/PriceFilter.vue")['default']
  'ResetFiltersButton': typeof import("../../woonuxt_base/app/components/filtering/ResetFiltersButton.vue")['default']
  'ShowFilterTrigger': typeof import("../../woonuxt_base/app/components/filtering/ShowFilterTrigger.vue")['default']
  'StarRatingFilter': typeof import("../../woonuxt_base/app/components/filtering/StarRatingFilter.vue")['default']
  'AddressSummary': typeof import("../../woonuxt_base/app/components/forms/AddressSummary.vue")['default']
  'BillingAndShipping': typeof import("../../woonuxt_base/app/components/forms/BillingAndShipping.vue")['default']
  'BillingDetails': typeof import("../../woonuxt_base/app/components/forms/BillingDetails.vue")['default']
  'ChangePassword': typeof import("../../woonuxt_base/app/components/forms/ChangePassword.vue")['default']
  'LoginAndRegister': typeof import("../../woonuxt_base/app/components/forms/LoginAndRegister.vue")['default']
  'LoginProviders': typeof import("../../woonuxt_base/app/components/forms/LoginProviders.vue")['default']
  'PasswordInput': typeof import("../../woonuxt_base/app/components/forms/PasswordInput.vue")['default']
  'PersonalInformation': typeof import("../../woonuxt_base/app/components/forms/PersonalInformation.vue")['default']
  'ResetPassword': typeof import("../../woonuxt_base/app/components/forms/ResetPassword.vue")['default']
  'ShippingDetails': typeof import("../../woonuxt_base/app/components/forms/ShippingDetails.vue")['default']
  'AppFooter': typeof import("../../woonuxt_base/app/components/generalElements/AppFooter.vue")['default']
  'AppHeader': typeof import("../../woonuxt_base/app/components/generalElements/AppHeader.vue")['default']
  'Breadcrumb': typeof import("../../woonuxt_base/app/components/generalElements/Breadcrumb.vue")['default']
  'HeroBanner': typeof import("../../woonuxt_base/app/components/generalElements/HeroBanner.vue")['default']
  'LoadingIcon': typeof import("../../woonuxt_base/app/components/generalElements/LoadingIcon.vue")['default']
  'Logo': typeof import("../../woonuxt_base/app/components/generalElements/Logo.vue")['default']
  'MainMenu': typeof import("../../woonuxt_base/app/components/generalElements/MainMenu.vue")['default']
  'MenuTrigger': typeof import("../../woonuxt_base/app/components/generalElements/MenuTrigger.vue")['default']
  'MobileMenu': typeof import("../../woonuxt_base/app/components/generalElements/MobileMenu.vue")['default']
  'SEOHead': typeof import("../../woonuxt_base/app/components/generalElements/SEOHead.vue")['default']
  'SearchTrigger': typeof import("../../woonuxt_base/app/components/generalElements/SearchTrigger.vue")['default']
  'SocialIcons': typeof import("../../woonuxt_base/app/components/generalElements/SocialIcons.vue")['default']
  'Tooltip': typeof import("../../woonuxt_base/app/components/generalElements/Tooltip.vue")['default']
  'AddToCartButton': typeof import("../../woonuxt_base/app/components/productElements/AddToCartButton.vue")['default']
  'AttributeSelections': typeof import("../../woonuxt_base/app/components/productElements/AttributeSelections.vue")['default']
  'ProductCard': typeof import("../../woonuxt_base/app/components/productElements/ProductCard.vue")['default']
  'ProductImageGallery': typeof import("../../woonuxt_base/app/components/productElements/ProductImageGallery.vue")['default']
  'ProductPrice': typeof import("../../woonuxt_base/app/components/productElements/ProductPrice.vue")['default']
  'ProductTabs': typeof import("../../woonuxt_base/app/components/productElements/ProductTabs.vue")['default']
  'ReviewsScore': typeof import("../../woonuxt_base/app/components/productElements/ReviewsScore.vue")['default']
  'SaleBadge': typeof import("../../woonuxt_base/app/components/productElements/SaleBadge.vue")['default']
  'ShareButton': typeof import("../../woonuxt_base/app/components/productElements/ShareButton.vue")['default']
  'StarRating': typeof import("../../woonuxt_base/app/components/productElements/StarRating.vue")['default']
  'StockStatus': typeof import("../../woonuxt_base/app/components/productElements/StockStatus.vue")['default']
  'WishlistButton': typeof import("../../woonuxt_base/app/components/productElements/WishlistButton.vue")['default']
  'AddCoupon': typeof import("../../woonuxt_base/app/components/shopElements/AddCoupon.vue")['default']
  'Cart': typeof import("../../woonuxt_base/app/components/shopElements/Cart.vue")['default']
  'CountrySelect': typeof import("../../woonuxt_base/app/components/shopElements/CountrySelect.vue")['default']
  'EmptyCartMessage': typeof import("../../woonuxt_base/app/components/shopElements/EmptyCartMessage.vue")['default']
  'NoProductsFound': typeof import("../../woonuxt_base/app/components/shopElements/NoProductsFound.vue")['default']
  'OrderByDropdown': typeof import("../../woonuxt_base/app/components/shopElements/OrderByDropdown.vue")['default']
  'OrderStatusLabel': typeof import("../../woonuxt_base/app/components/shopElements/OrderStatusLabel.vue")['default']
  'OrderSummary': typeof import("../../woonuxt_base/app/components/shopElements/OrderSummary.vue")['default']
  'Pagination': typeof import("../../woonuxt_base/app/components/shopElements/Pagination.vue")['default']
  'PaymentOptions': typeof import("../../woonuxt_base/app/components/shopElements/PaymentOptions.vue")['default']
  'ProductGrid': typeof import("../../woonuxt_base/app/components/shopElements/ProductGrid.vue")['default']
  'ProductResultCount': typeof import("../../woonuxt_base/app/components/shopElements/ProductResultCount.vue")['default']
  'ProductReviews': typeof import("../../woonuxt_base/app/components/shopElements/ProductReviews.vue")['default']
  'ProductRow': typeof import("../../woonuxt_base/app/components/shopElements/ProductRow.vue")['default']
  'ProductSearch': typeof import("../../woonuxt_base/app/components/shopElements/ProductSearch.vue")['default']
  'ShippingOptions': typeof import("../../woonuxt_base/app/components/shopElements/ShippingOptions.vue")['default']
  'StateSelect': typeof import("../../woonuxt_base/app/components/shopElements/StateSelect.vue")['default']
  'StripeElement': typeof import("../../woonuxt_base/app/components/shopElements/StripeElement.vue")['default']
  'WebsiteShortDescription': typeof import("../../woonuxt_base/app/components/shopElements/WebsiteShortDescription.vue")['default']
  'WishList': typeof import("../../woonuxt_base/app/components/shopElements/WishList.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  'NuxtLinkLocale': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  'SwitchLocalePathLink': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyAccountMyDetails': LazyComponent<typeof import("../../woonuxt_base/app/components/AccountMyDetails.vue")['default']>
  'LazyCategoryCard': LazyComponent<typeof import("../../woonuxt_base/app/components/CategoryCard.vue")['default']>
  'LazyDownloadList': LazyComponent<typeof import("../../woonuxt_base/app/components/DownloadList.vue")['default']>
  'LazyDownloadableItems': LazyComponent<typeof import("../../woonuxt_base/app/components/DownloadableItems.vue")['default']>
  'LazyLangSwitcher': LazyComponent<typeof import("../../woonuxt_base/app/components/LangSwitcher.vue")['default']>
  'LazyOrderList': LazyComponent<typeof import("../../woonuxt_base/app/components/OrderList.vue")['default']>
  'LazySignInLink': LazyComponent<typeof import("../../woonuxt_base/app/components/SignInLink.vue")['default']>
  'LazyWPAdminLink': LazyComponent<typeof import("../../woonuxt_base/app/components/WPAdminLink.vue")['default']>
  'LazyWishListItem': LazyComponent<typeof import("../../woonuxt_base/app/components/WishListItem.vue")['default']>
  'LazyCartCard': LazyComponent<typeof import("../../woonuxt_base/app/components/cartElements/CartCard.vue")['default']>
  'LazyCartTrigger': LazyComponent<typeof import("../../woonuxt_base/app/components/cartElements/CartTrigger.vue")['default']>
  'LazyCloseIcon': LazyComponent<typeof import("../../woonuxt_base/app/components/cartElements/CloseIcon.vue")['default']>
  'LazyEmptyCart': LazyComponent<typeof import("../../woonuxt_base/app/components/cartElements/EmptyCart.vue")['default']>
  'LazyQuantityInput': LazyComponent<typeof import("../../woonuxt_base/app/components/cartElements/QuantityInput.vue")['default']>
  'LazySwipeCard': LazyComponent<typeof import("../../woonuxt_base/app/components/cartElements/SwipeCard.vue")['default']>
  'LazyTrashIcon': LazyComponent<typeof import("../../woonuxt_base/app/components/cartElements/TrashIcon.vue")['default']>
  'LazyCategoryFilter': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/CategoryFilter.vue")['default']>
  'LazyColorFilter': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/ColorFilter.vue")['default']>
  'LazyFilters': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/Filters.vue")['default']>
  'LazyGlobalFilter': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/GlobalFilter.vue")['default']>
  'LazyOnSaleFilter': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/OnSaleFilter.vue")['default']>
  'LazyPriceFilter': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/PriceFilter.vue")['default']>
  'LazyResetFiltersButton': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/ResetFiltersButton.vue")['default']>
  'LazyShowFilterTrigger': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/ShowFilterTrigger.vue")['default']>
  'LazyStarRatingFilter': LazyComponent<typeof import("../../woonuxt_base/app/components/filtering/StarRatingFilter.vue")['default']>
  'LazyAddressSummary': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/AddressSummary.vue")['default']>
  'LazyBillingAndShipping': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/BillingAndShipping.vue")['default']>
  'LazyBillingDetails': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/BillingDetails.vue")['default']>
  'LazyChangePassword': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/ChangePassword.vue")['default']>
  'LazyLoginAndRegister': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/LoginAndRegister.vue")['default']>
  'LazyLoginProviders': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/LoginProviders.vue")['default']>
  'LazyPasswordInput': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/PasswordInput.vue")['default']>
  'LazyPersonalInformation': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/PersonalInformation.vue")['default']>
  'LazyResetPassword': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/ResetPassword.vue")['default']>
  'LazyShippingDetails': LazyComponent<typeof import("../../woonuxt_base/app/components/forms/ShippingDetails.vue")['default']>
  'LazyAppFooter': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/AppFooter.vue")['default']>
  'LazyAppHeader': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/AppHeader.vue")['default']>
  'LazyBreadcrumb': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/Breadcrumb.vue")['default']>
  'LazyHeroBanner': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/HeroBanner.vue")['default']>
  'LazyLoadingIcon': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/LoadingIcon.vue")['default']>
  'LazyLogo': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/Logo.vue")['default']>
  'LazyMainMenu': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/MainMenu.vue")['default']>
  'LazyMenuTrigger': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/MenuTrigger.vue")['default']>
  'LazyMobileMenu': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/MobileMenu.vue")['default']>
  'LazySEOHead': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/SEOHead.vue")['default']>
  'LazySearchTrigger': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/SearchTrigger.vue")['default']>
  'LazySocialIcons': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/SocialIcons.vue")['default']>
  'LazyTooltip': LazyComponent<typeof import("../../woonuxt_base/app/components/generalElements/Tooltip.vue")['default']>
  'LazyAddToCartButton': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/AddToCartButton.vue")['default']>
  'LazyAttributeSelections': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/AttributeSelections.vue")['default']>
  'LazyProductCard': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/ProductCard.vue")['default']>
  'LazyProductImageGallery': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/ProductImageGallery.vue")['default']>
  'LazyProductPrice': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/ProductPrice.vue")['default']>
  'LazyProductTabs': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/ProductTabs.vue")['default']>
  'LazyReviewsScore': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/ReviewsScore.vue")['default']>
  'LazySaleBadge': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/SaleBadge.vue")['default']>
  'LazyShareButton': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/ShareButton.vue")['default']>
  'LazyStarRating': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/StarRating.vue")['default']>
  'LazyStockStatus': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/StockStatus.vue")['default']>
  'LazyWishlistButton': LazyComponent<typeof import("../../woonuxt_base/app/components/productElements/WishlistButton.vue")['default']>
  'LazyAddCoupon': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/AddCoupon.vue")['default']>
  'LazyCart': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/Cart.vue")['default']>
  'LazyCountrySelect': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/CountrySelect.vue")['default']>
  'LazyEmptyCartMessage': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/EmptyCartMessage.vue")['default']>
  'LazyNoProductsFound': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/NoProductsFound.vue")['default']>
  'LazyOrderByDropdown': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/OrderByDropdown.vue")['default']>
  'LazyOrderStatusLabel': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/OrderStatusLabel.vue")['default']>
  'LazyOrderSummary': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/OrderSummary.vue")['default']>
  'LazyPagination': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/Pagination.vue")['default']>
  'LazyPaymentOptions': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/PaymentOptions.vue")['default']>
  'LazyProductGrid': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/ProductGrid.vue")['default']>
  'LazyProductResultCount': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/ProductResultCount.vue")['default']>
  'LazyProductReviews': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/ProductReviews.vue")['default']>
  'LazyProductRow': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/ProductRow.vue")['default']>
  'LazyProductSearch': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/ProductSearch.vue")['default']>
  'LazyShippingOptions': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/ShippingOptions.vue")['default']>
  'LazyStateSelect': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/StateSelect.vue")['default']>
  'LazyStripeElement': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/StripeElement.vue")['default']>
  'LazyWebsiteShortDescription': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/WebsiteShortDescription.vue")['default']>
  'LazyWishList': LazyComponent<typeof import("../../woonuxt_base/app/components/shopElements/WishList.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
